plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bokhaled.tv'
    compileSdk 36

    defaultConfig {
        applicationId "com.bokhaled.tv"
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName "3.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation "androidx.media3:media3-exoplayer:1.11.0"
    implementation "androidx.media3:media3-exoplayer-hls:1.11.0"
    implementation "androidx.media3:media3-ui:1.11.0"
}
